const products = [
    {
        id: "1",
        image: "/i1.png",
        name: "Nike Air Force 1 Mid'07",
        price: "10 795.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "2",
        image: "/i2.png",
        name: "Nike Court Vision Low Next Nature",
        price: "4 995.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "3",
        image: "/i3.png",
        name: "Nike Air Force 1 PLATFORM",
        price: "8 695.00",
        color: "1 color",
        type: "Women's Shoes",
        status: "Just In",
    },
    {
        id: "4",
        image: "/i4.png",
        name: "Nike Air Force 1 React",
        price: "13 295.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "5",
        image: "/i5.png",
        name: "Air Jordan 1 Elevate Low",
        price: "11 895.000",
        color: "1 color",
        type: "Women's Shoes",
        status: "Promo Exclusion",
    },
    {
        id: "6",
        image: "/i6.png",
        name: "Nike Air Force 1 Mid'07",
        price: "10 795.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "7",
        image: "/i7.png",
        name: "Nike Dunk Low Retro SE",
        price: "9 695.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Promo Exclusion",
    },
    {
        id: "8",
        image: "/i8.png",
        name: "Nike Dri-FIT UV Hyverse",
        price: "2 495.00",
        color: "1 color",
        type: "Men's Short-Sleeve Graphic Fitness Top",
        status: "Sustainable Matarials",
    },
    {
        id: "9",
        image: "/i9.png",
        name: "Nike Court Vision Low",
        price: "5 695.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "10",
        image: "/i10.png",
        name: "Nike Dri-FIT Ready",
        price: "2 495.00",
        color: "3 color",
        type: "Men's Short-Sleeve Fitness Top",
        status: "Just In",
    },
    {
        id: "11",
        image: "/i11.png",
        name: "Nike One Leak Protection: Period",
        price: "3 395.00",
        color: "2 color",
        type: "Women's Mid-Rise 18cm (approx.) Biker Shorts",
        status: "Just In",
    },
    {
        id: "12",
        image: "/i12.png",
        name: "Nike Air Force 1 LV8 3",
        price: "7 495.00",
        color: "1 color",
        type: "Older Kids' Shoe",
        status: "Just In",
    },
    {
        id: "13",
        image: "/i13.png",
        name: "Nike Blazer Low Platform",
        price: "8 195.00",
        color: "1 color",
        type: "Women's Shoes",
        status: "Just In",
    },
    {
        id: "14",
        image: "/i14.png",
        name: "Nike Air Force 1 '07",
        price: "8 195.00",
        color: "2 color",
        type: "Women's Shoe",
        status: "Just In",
    },
    {
        id: "15",
        image: "/i15.png",
        name: "Nike Pro Dri-FIT",
        price: "1 495.00",
        color: "1 color",
        type: "Men's Tight-Fit Sleeveless Top",
        status: "Just In",
    },
    {
        id: "16",
        image: "/i16.png",
        name: "Nike Dunk Low Retro",
        price: "8 695.00",
        color: "1 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "17",
        image: "/i17.png",
        name: "Nike Air Max SC",
        price: "5 995.00",
        color: "2 color",
        type: "Men's Shoes",
        status: "Just In",
    },
    {
        id: "18",
        image: "/i18.png",
        name: "Nike Dri-FIT UV Miler",
        price: "1 695.00",
        color: "1 color",
        type: "Men's Short-Sleeve Running Top",
        status: "Just In",
    },
    {
        id: "19",
        image: "/i19.png",
        name: "Nike Air Max SYSTM",
        price: "6 495.00",
        color: "1 color",
        type: "Older Kids' Shoes",
        status: "Just In",
    },
    {
        id: "20",
        image: "/i20.png",
        name: "Nike Alate All U",
        price: "2 195.00",
        color: "1 color",
        type: "Women's Light-Support Lightly Lined U-Neck Printed Sports Bra",
        status: "Just In",
    },
    {
        id: "21",
        image: "/i21.png",
        name: "Nike Court Legacy Lift",
        price: "7 495.00",
        color: "2 color",
        type: "Women's Shoes",
        status: "Just In",
    },
    {
        id: "22",
        image: "/i22.png",
        name: "Nike Swoosh",
        price: "3 095.00",
        color: "2 color",
        type: "Women's Medium-support Padded Sports Bra Tank",
        status: "Just In",
    },
    {
        id: "23",
        image: "/i23.png",
        name: "Nike SB Zoom Janoski OG+",
        price: "8 595.00",
        color: "1 color",
        type: "Shoes",
        status: "Just In",
    },
    {
        id: "24",
        image: "/i24.png",
        name: "Nike Dri-FIT Run Division Rise 365",
        price: "3 495.00",
        color: "2 color",
        type: "Men's Running Tank",
        status: "Just In",
    },
    {
        id: "25",
        image: "/i25.png",
        name: "Nike Dri-FIT Challenger",
        price: "2 495.00",
        color: "1 color",
        type: "Men's 18cm (approx.) 2-in-1 Versatile Shorts",
        status: "Just In",
    },
    {
        id: "26",
        image: "/i26.png",
        name: "Jordan Series ES",
        price: "7 495.00",
        color: "2 color",
        type: "Men's Shoe",
        status: "Just In",
    },
    {
        id: "27",
        image: "/i27.png",
        name: "Nike Outdoor Play",
        price: "3 895.00",
        color: "1 color",
        type: "Older Kids' Oversized Woven Jacket",
        status: "Just In",
    },
    {
        id: "28",
        image: "/i28.png",
        name: "Nike Sportswear Trend",
        price: "2 495.00",
        color: "2 color",
        type: "Older Kids' (Girls') High-waisted Woven Shorts",
        status: "Just In",
    },
    {
        id: "29",
        image: "/i29.png",
        name: "Nike Blazer Low &apos;77 Jumbo",
        price: "8 595.00",
        color: "1 color",
        type: "Women's Shoes",
        status: "Just In",
    },
    {
        id: "30",
        image: "/i30.png",
        name: "Nike SB Force 58",
        price: "5 995.00",
        color: "1 color",
        type: "Skate Shoe",
        status: "Just In",
    },
];

export default products;