import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FooterHandler from "@/components/FooterHandler";
import HeaderHandler from "@/components/HeaderHandler";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nike UI - Free UI kit (Recreated) (Community)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <WishlistProvider>
            <HeaderHandler />
            <main className="mt-5 mb-5">{children}</main>
            <FooterHandler />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
